// Code generated by genrequestvalidation. DO NOT EDIT.
package validation

import (
	"context"

	pb0 "go.temporal.io/api/operatorservice/v1"
	pb1 "go.temporal.io/api/workflowservice/v1"
)

var generatedUnaryMethods = map[string]struct{}{
	"/temporal.api.operatorservice.v1.OperatorService/AddSearchAttributes":                          {},
	"/temporal.api.operatorservice.v1.OperatorService/RemoveSearchAttributes":                       {},
	"/temporal.api.operatorservice.v1.OperatorService/ListSearchAttributes":                         {},
	"/temporal.api.operatorservice.v1.OperatorService/DeleteNamespace":                              {},
	"/temporal.api.operatorservice.v1.OperatorService/AddOrUpdateRemoteCluster":                     {},
	"/temporal.api.operatorservice.v1.OperatorService/RemoveRemoteCluster":                          {},
	"/temporal.api.operatorservice.v1.OperatorService/ListClusters":                                 {},
	"/temporal.api.operatorservice.v1.OperatorService/GetNexusEndpoint":                             {},
	"/temporal.api.operatorservice.v1.OperatorService/CreateNexusEndpoint":                          {},
	"/temporal.api.operatorservice.v1.OperatorService/UpdateNexusEndpoint":                          {},
	"/temporal.api.operatorservice.v1.OperatorService/DeleteNexusEndpoint":                          {},
	"/temporal.api.operatorservice.v1.OperatorService/ListNexusEndpoints":                           {},
	"/temporal.api.workflowservice.v1.WorkflowService/RegisterNamespace":                            {},
	"/temporal.api.workflowservice.v1.WorkflowService/DescribeNamespace":                            {},
	"/temporal.api.workflowservice.v1.WorkflowService/ListNamespaces":                               {},
	"/temporal.api.workflowservice.v1.WorkflowService/UpdateNamespace":                              {},
	"/temporal.api.workflowservice.v1.WorkflowService/DeprecateNamespace":                           {},
	"/temporal.api.workflowservice.v1.WorkflowService/StartWorkflowExecution":                       {},
	"/temporal.api.workflowservice.v1.WorkflowService/ExecuteMultiOperation":                        {},
	"/temporal.api.workflowservice.v1.WorkflowService/GetWorkflowExecutionHistory":                  {},
	"/temporal.api.workflowservice.v1.WorkflowService/GetWorkflowExecutionHistoryReverse":           {},
	"/temporal.api.workflowservice.v1.WorkflowService/PollWorkflowTaskQueue":                        {},
	"/temporal.api.workflowservice.v1.WorkflowService/RespondWorkflowTaskCompleted":                 {},
	"/temporal.api.workflowservice.v1.WorkflowService/RespondWorkflowTaskFailed":                    {},
	"/temporal.api.workflowservice.v1.WorkflowService/PollActivityTaskQueue":                        {},
	"/temporal.api.workflowservice.v1.WorkflowService/RecordActivityTaskHeartbeat":                  {},
	"/temporal.api.workflowservice.v1.WorkflowService/RecordActivityTaskHeartbeatById":              {},
	"/temporal.api.workflowservice.v1.WorkflowService/RespondActivityTaskCompleted":                 {},
	"/temporal.api.workflowservice.v1.WorkflowService/RespondActivityTaskCompletedById":             {},
	"/temporal.api.workflowservice.v1.WorkflowService/RespondActivityTaskFailed":                    {},
	"/temporal.api.workflowservice.v1.WorkflowService/RespondActivityTaskFailedById":                {},
	"/temporal.api.workflowservice.v1.WorkflowService/RespondActivityTaskCanceled":                  {},
	"/temporal.api.workflowservice.v1.WorkflowService/RespondActivityTaskCanceledById":              {},
	"/temporal.api.workflowservice.v1.WorkflowService/RequestCancelWorkflowExecution":               {},
	"/temporal.api.workflowservice.v1.WorkflowService/SignalWorkflowExecution":                      {},
	"/temporal.api.workflowservice.v1.WorkflowService/SignalWithStartWorkflowExecution":             {},
	"/temporal.api.workflowservice.v1.WorkflowService/ResetWorkflowExecution":                       {},
	"/temporal.api.workflowservice.v1.WorkflowService/TerminateWorkflowExecution":                   {},
	"/temporal.api.workflowservice.v1.WorkflowService/DeleteWorkflowExecution":                      {},
	"/temporal.api.workflowservice.v1.WorkflowService/ListOpenWorkflowExecutions":                   {},
	"/temporal.api.workflowservice.v1.WorkflowService/ListClosedWorkflowExecutions":                 {},
	"/temporal.api.workflowservice.v1.WorkflowService/ListWorkflowExecutions":                       {},
	"/temporal.api.workflowservice.v1.WorkflowService/ListArchivedWorkflowExecutions":               {},
	"/temporal.api.workflowservice.v1.WorkflowService/ScanWorkflowExecutions":                       {},
	"/temporal.api.workflowservice.v1.WorkflowService/CountWorkflowExecutions":                      {},
	"/temporal.api.workflowservice.v1.WorkflowService/GetSearchAttributes":                          {},
	"/temporal.api.workflowservice.v1.WorkflowService/RespondQueryTaskCompleted":                    {},
	"/temporal.api.workflowservice.v1.WorkflowService/ResetStickyTaskQueue":                         {},
	"/temporal.api.workflowservice.v1.WorkflowService/ShutdownWorker":                               {},
	"/temporal.api.workflowservice.v1.WorkflowService/QueryWorkflow":                                {},
	"/temporal.api.workflowservice.v1.WorkflowService/DescribeWorkflowExecution":                    {},
	"/temporal.api.workflowservice.v1.WorkflowService/DescribeTaskQueue":                            {},
	"/temporal.api.workflowservice.v1.WorkflowService/GetClusterInfo":                               {},
	"/temporal.api.workflowservice.v1.WorkflowService/GetSystemInfo":                                {},
	"/temporal.api.workflowservice.v1.WorkflowService/ListTaskQueuePartitions":                      {},
	"/temporal.api.workflowservice.v1.WorkflowService/CreateSchedule":                               {},
	"/temporal.api.workflowservice.v1.WorkflowService/DescribeSchedule":                             {},
	"/temporal.api.workflowservice.v1.WorkflowService/UpdateSchedule":                               {},
	"/temporal.api.workflowservice.v1.WorkflowService/PatchSchedule":                                {},
	"/temporal.api.workflowservice.v1.WorkflowService/ListScheduleMatchingTimes":                    {},
	"/temporal.api.workflowservice.v1.WorkflowService/DeleteSchedule":                               {},
	"/temporal.api.workflowservice.v1.WorkflowService/ListSchedules":                                {},
	"/temporal.api.workflowservice.v1.WorkflowService/CountSchedules":                               {},
	"/temporal.api.workflowservice.v1.WorkflowService/UpdateWorkerBuildIdCompatibility":             {},
	"/temporal.api.workflowservice.v1.WorkflowService/GetWorkerBuildIdCompatibility":                {},
	"/temporal.api.workflowservice.v1.WorkflowService/UpdateWorkerVersioningRules":                  {},
	"/temporal.api.workflowservice.v1.WorkflowService/GetWorkerVersioningRules":                     {},
	"/temporal.api.workflowservice.v1.WorkflowService/GetWorkerTaskReachability":                    {},
	"/temporal.api.workflowservice.v1.WorkflowService/DescribeDeployment":                           {},
	"/temporal.api.workflowservice.v1.WorkflowService/DescribeWorkerDeploymentVersion":              {},
	"/temporal.api.workflowservice.v1.WorkflowService/ListDeployments":                              {},
	"/temporal.api.workflowservice.v1.WorkflowService/GetDeploymentReachability":                    {},
	"/temporal.api.workflowservice.v1.WorkflowService/GetCurrentDeployment":                         {},
	"/temporal.api.workflowservice.v1.WorkflowService/SetCurrentDeployment":                         {},
	"/temporal.api.workflowservice.v1.WorkflowService/SetWorkerDeploymentCurrentVersion":            {},
	"/temporal.api.workflowservice.v1.WorkflowService/DescribeWorkerDeployment":                     {},
	"/temporal.api.workflowservice.v1.WorkflowService/DeleteWorkerDeployment":                       {},
	"/temporal.api.workflowservice.v1.WorkflowService/DeleteWorkerDeploymentVersion":                {},
	"/temporal.api.workflowservice.v1.WorkflowService/SetWorkerDeploymentRampingVersion":            {},
	"/temporal.api.workflowservice.v1.WorkflowService/ListWorkerDeployments":                        {},
	"/temporal.api.workflowservice.v1.WorkflowService/CreateWorkerDeployment":                       {},
	"/temporal.api.workflowservice.v1.WorkflowService/CreateWorkerDeploymentVersion":                {},
	"/temporal.api.workflowservice.v1.WorkflowService/UpdateWorkerDeploymentVersionComputeConfig":   {},
	"/temporal.api.workflowservice.v1.WorkflowService/ValidateWorkerDeploymentVersionComputeConfig": {},
	"/temporal.api.workflowservice.v1.WorkflowService/UpdateWorkerDeploymentVersionMetadata":        {},
	"/temporal.api.workflowservice.v1.WorkflowService/SetWorkerDeploymentManager":                   {},
	"/temporal.api.workflowservice.v1.WorkflowService/UpdateWorkflowExecution":                      {},
	"/temporal.api.workflowservice.v1.WorkflowService/PollWorkflowExecutionUpdate":                  {},
	"/temporal.api.workflowservice.v1.WorkflowService/StartBatchOperation":                          {},
	"/temporal.api.workflowservice.v1.WorkflowService/StopBatchOperation":                           {},
	"/temporal.api.workflowservice.v1.WorkflowService/DescribeBatchOperation":                       {},
	"/temporal.api.workflowservice.v1.WorkflowService/ListBatchOperations":                          {},
	"/temporal.api.workflowservice.v1.WorkflowService/PollNexusTaskQueue":                           {},
	"/temporal.api.workflowservice.v1.WorkflowService/RespondNexusTaskCompleted":                    {},
	"/temporal.api.workflowservice.v1.WorkflowService/RespondNexusTaskFailed":                       {},
	"/temporal.api.workflowservice.v1.WorkflowService/UpdateActivityOptions":                        {},
	"/temporal.api.workflowservice.v1.WorkflowService/UpdateWorkflowExecutionOptions":               {},
	"/temporal.api.workflowservice.v1.WorkflowService/PauseActivity":                                {},
	"/temporal.api.workflowservice.v1.WorkflowService/UnpauseActivity":                              {},
	"/temporal.api.workflowservice.v1.WorkflowService/ResetActivity":                                {},
	"/temporal.api.workflowservice.v1.WorkflowService/CreateWorkflowRule":                           {},
	"/temporal.api.workflowservice.v1.WorkflowService/DescribeWorkflowRule":                         {},
	"/temporal.api.workflowservice.v1.WorkflowService/DeleteWorkflowRule":                           {},
	"/temporal.api.workflowservice.v1.WorkflowService/ListWorkflowRules":                            {},
	"/temporal.api.workflowservice.v1.WorkflowService/TriggerWorkflowRule":                          {},
	"/temporal.api.workflowservice.v1.WorkflowService/RecordWorkerHeartbeat":                        {},
	"/temporal.api.workflowservice.v1.WorkflowService/ListWorkers":                                  {},
	"/temporal.api.workflowservice.v1.WorkflowService/CountWorkers":                                 {},
	"/temporal.api.workflowservice.v1.WorkflowService/UpdateTaskQueueConfig":                        {},
	"/temporal.api.workflowservice.v1.WorkflowService/FetchWorkerConfig":                            {},
	"/temporal.api.workflowservice.v1.WorkflowService/UpdateWorkerConfig":                           {},
	"/temporal.api.workflowservice.v1.WorkflowService/DescribeWorker":                               {},
	"/temporal.api.workflowservice.v1.WorkflowService/PauseWorkflowExecution":                       {},
	"/temporal.api.workflowservice.v1.WorkflowService/UnpauseWorkflowExecution":                     {},
	"/temporal.api.workflowservice.v1.WorkflowService/StartActivityExecution":                       {},
	"/temporal.api.workflowservice.v1.WorkflowService/StartNexusOperationExecution":                 {},
	"/temporal.api.workflowservice.v1.WorkflowService/DescribeActivityExecution":                    {},
	"/temporal.api.workflowservice.v1.WorkflowService/DescribeNexusOperationExecution":              {},
	"/temporal.api.workflowservice.v1.WorkflowService/PollActivityExecution":                        {},
	"/temporal.api.workflowservice.v1.WorkflowService/PollNexusOperationExecution":                  {},
	"/temporal.api.workflowservice.v1.WorkflowService/ListActivityExecutions":                       {},
	"/temporal.api.workflowservice.v1.WorkflowService/ListNexusOperationExecutions":                 {},
	"/temporal.api.workflowservice.v1.WorkflowService/CountActivityExecutions":                      {},
	"/temporal.api.workflowservice.v1.WorkflowService/CountNexusOperationExecutions":                {},
	"/temporal.api.workflowservice.v1.WorkflowService/RequestCancelActivityExecution":               {},
	"/temporal.api.workflowservice.v1.WorkflowService/RequestCancelNexusOperationExecution":         {},
	"/temporal.api.workflowservice.v1.WorkflowService/TerminateActivityExecution":                   {},
	"/temporal.api.workflowservice.v1.WorkflowService/DeleteActivityExecution":                      {},
	"/temporal.api.workflowservice.v1.WorkflowService/PauseActivityExecution":                       {},
	"/temporal.api.workflowservice.v1.WorkflowService/ResetActivityExecution":                       {},
	"/temporal.api.workflowservice.v1.WorkflowService/UnpauseActivityExecution":                     {},
	"/temporal.api.workflowservice.v1.WorkflowService/UpdateActivityExecutionOptions":               {},
	"/temporal.api.workflowservice.v1.WorkflowService/TerminateNexusOperationExecution":             {},
	"/temporal.api.workflowservice.v1.WorkflowService/DeleteNexusOperationExecution":                {},
	"/temporal.api.workflowservice.v1.WorkflowService/PollWorkflowExecutionTimeSkipping":            {},
}

type validatedOperatorService struct {
	pb0.OperatorServiceServer
	registry *Registry
}

func WrapOperatorService(handler pb0.OperatorServiceServer, registry *Registry) pb0.OperatorServiceServer {
	return &validatedOperatorService{OperatorServiceServer: handler, registry: registry}
}
func (h *validatedOperatorService) AddSearchAttributes(ctx context.Context, request *pb0.AddSearchAttributesRequest) (*pb0.AddSearchAttributesResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.operatorservice.v1.OperatorService/AddSearchAttributes", request, h.OperatorServiceServer.AddSearchAttributes)
}
func (h *validatedOperatorService) RemoveSearchAttributes(ctx context.Context, request *pb0.RemoveSearchAttributesRequest) (*pb0.RemoveSearchAttributesResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.operatorservice.v1.OperatorService/RemoveSearchAttributes", request, h.OperatorServiceServer.RemoveSearchAttributes)
}
func (h *validatedOperatorService) ListSearchAttributes(ctx context.Context, request *pb0.ListSearchAttributesRequest) (*pb0.ListSearchAttributesResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.operatorservice.v1.OperatorService/ListSearchAttributes", request, h.OperatorServiceServer.ListSearchAttributes)
}
func (h *validatedOperatorService) DeleteNamespace(ctx context.Context, request *pb0.DeleteNamespaceRequest) (*pb0.DeleteNamespaceResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.operatorservice.v1.OperatorService/DeleteNamespace", request, h.OperatorServiceServer.DeleteNamespace)
}
func (h *validatedOperatorService) AddOrUpdateRemoteCluster(ctx context.Context, request *pb0.AddOrUpdateRemoteClusterRequest) (*pb0.AddOrUpdateRemoteClusterResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.operatorservice.v1.OperatorService/AddOrUpdateRemoteCluster", request, h.OperatorServiceServer.AddOrUpdateRemoteCluster)
}
func (h *validatedOperatorService) RemoveRemoteCluster(ctx context.Context, request *pb0.RemoveRemoteClusterRequest) (*pb0.RemoveRemoteClusterResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.operatorservice.v1.OperatorService/RemoveRemoteCluster", request, h.OperatorServiceServer.RemoveRemoteCluster)
}
func (h *validatedOperatorService) ListClusters(ctx context.Context, request *pb0.ListClustersRequest) (*pb0.ListClustersResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.operatorservice.v1.OperatorService/ListClusters", request, h.OperatorServiceServer.ListClusters)
}
func (h *validatedOperatorService) GetNexusEndpoint(ctx context.Context, request *pb0.GetNexusEndpointRequest) (*pb0.GetNexusEndpointResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.operatorservice.v1.OperatorService/GetNexusEndpoint", request, h.OperatorServiceServer.GetNexusEndpoint)
}
func (h *validatedOperatorService) CreateNexusEndpoint(ctx context.Context, request *pb0.CreateNexusEndpointRequest) (*pb0.CreateNexusEndpointResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.operatorservice.v1.OperatorService/CreateNexusEndpoint", request, h.OperatorServiceServer.CreateNexusEndpoint)
}
func (h *validatedOperatorService) UpdateNexusEndpoint(ctx context.Context, request *pb0.UpdateNexusEndpointRequest) (*pb0.UpdateNexusEndpointResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.operatorservice.v1.OperatorService/UpdateNexusEndpoint", request, h.OperatorServiceServer.UpdateNexusEndpoint)
}
func (h *validatedOperatorService) DeleteNexusEndpoint(ctx context.Context, request *pb0.DeleteNexusEndpointRequest) (*pb0.DeleteNexusEndpointResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.operatorservice.v1.OperatorService/DeleteNexusEndpoint", request, h.OperatorServiceServer.DeleteNexusEndpoint)
}
func (h *validatedOperatorService) ListNexusEndpoints(ctx context.Context, request *pb0.ListNexusEndpointsRequest) (*pb0.ListNexusEndpointsResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.operatorservice.v1.OperatorService/ListNexusEndpoints", request, h.OperatorServiceServer.ListNexusEndpoints)
}

type validatedWorkflowService struct {
	pb1.WorkflowServiceServer
	registry *Registry
}

func WrapWorkflowService(handler pb1.WorkflowServiceServer, registry *Registry) pb1.WorkflowServiceServer {
	return &validatedWorkflowService{WorkflowServiceServer: handler, registry: registry}
}
func (h *validatedWorkflowService) RegisterNamespace(ctx context.Context, request *pb1.RegisterNamespaceRequest) (*pb1.RegisterNamespaceResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/RegisterNamespace", request, h.WorkflowServiceServer.RegisterNamespace)
}
func (h *validatedWorkflowService) DescribeNamespace(ctx context.Context, request *pb1.DescribeNamespaceRequest) (*pb1.DescribeNamespaceResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/DescribeNamespace", request, h.WorkflowServiceServer.DescribeNamespace)
}
func (h *validatedWorkflowService) ListNamespaces(ctx context.Context, request *pb1.ListNamespacesRequest) (*pb1.ListNamespacesResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/ListNamespaces", request, h.WorkflowServiceServer.ListNamespaces)
}
func (h *validatedWorkflowService) UpdateNamespace(ctx context.Context, request *pb1.UpdateNamespaceRequest) (*pb1.UpdateNamespaceResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/UpdateNamespace", request, h.WorkflowServiceServer.UpdateNamespace)
}
func (h *validatedWorkflowService) DeprecateNamespace(ctx context.Context, request *pb1.DeprecateNamespaceRequest) (*pb1.DeprecateNamespaceResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/DeprecateNamespace", request, h.WorkflowServiceServer.DeprecateNamespace)
}
func (h *validatedWorkflowService) StartWorkflowExecution(ctx context.Context, request *pb1.StartWorkflowExecutionRequest) (*pb1.StartWorkflowExecutionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/StartWorkflowExecution", request, h.WorkflowServiceServer.StartWorkflowExecution)
}
func (h *validatedWorkflowService) ExecuteMultiOperation(ctx context.Context, request *pb1.ExecuteMultiOperationRequest) (*pb1.ExecuteMultiOperationResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/ExecuteMultiOperation", request, h.WorkflowServiceServer.ExecuteMultiOperation)
}
func (h *validatedWorkflowService) GetWorkflowExecutionHistory(ctx context.Context, request *pb1.GetWorkflowExecutionHistoryRequest) (*pb1.GetWorkflowExecutionHistoryResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/GetWorkflowExecutionHistory", request, h.WorkflowServiceServer.GetWorkflowExecutionHistory)
}
func (h *validatedWorkflowService) GetWorkflowExecutionHistoryReverse(ctx context.Context, request *pb1.GetWorkflowExecutionHistoryReverseRequest) (*pb1.GetWorkflowExecutionHistoryReverseResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/GetWorkflowExecutionHistoryReverse", request, h.WorkflowServiceServer.GetWorkflowExecutionHistoryReverse)
}
func (h *validatedWorkflowService) PollWorkflowTaskQueue(ctx context.Context, request *pb1.PollWorkflowTaskQueueRequest) (*pb1.PollWorkflowTaskQueueResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/PollWorkflowTaskQueue", request, h.WorkflowServiceServer.PollWorkflowTaskQueue)
}
func (h *validatedWorkflowService) RespondWorkflowTaskCompleted(ctx context.Context, request *pb1.RespondWorkflowTaskCompletedRequest) (*pb1.RespondWorkflowTaskCompletedResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/RespondWorkflowTaskCompleted", request, h.WorkflowServiceServer.RespondWorkflowTaskCompleted)
}
func (h *validatedWorkflowService) RespondWorkflowTaskFailed(ctx context.Context, request *pb1.RespondWorkflowTaskFailedRequest) (*pb1.RespondWorkflowTaskFailedResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/RespondWorkflowTaskFailed", request, h.WorkflowServiceServer.RespondWorkflowTaskFailed)
}
func (h *validatedWorkflowService) PollActivityTaskQueue(ctx context.Context, request *pb1.PollActivityTaskQueueRequest) (*pb1.PollActivityTaskQueueResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/PollActivityTaskQueue", request, h.WorkflowServiceServer.PollActivityTaskQueue)
}
func (h *validatedWorkflowService) RecordActivityTaskHeartbeat(ctx context.Context, request *pb1.RecordActivityTaskHeartbeatRequest) (*pb1.RecordActivityTaskHeartbeatResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/RecordActivityTaskHeartbeat", request, h.WorkflowServiceServer.RecordActivityTaskHeartbeat)
}
func (h *validatedWorkflowService) RecordActivityTaskHeartbeatById(ctx context.Context, request *pb1.RecordActivityTaskHeartbeatByIdRequest) (*pb1.RecordActivityTaskHeartbeatByIdResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/RecordActivityTaskHeartbeatById", request, h.WorkflowServiceServer.RecordActivityTaskHeartbeatById)
}
func (h *validatedWorkflowService) RespondActivityTaskCompleted(ctx context.Context, request *pb1.RespondActivityTaskCompletedRequest) (*pb1.RespondActivityTaskCompletedResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/RespondActivityTaskCompleted", request, h.WorkflowServiceServer.RespondActivityTaskCompleted)
}
func (h *validatedWorkflowService) RespondActivityTaskCompletedById(ctx context.Context, request *pb1.RespondActivityTaskCompletedByIdRequest) (*pb1.RespondActivityTaskCompletedByIdResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/RespondActivityTaskCompletedById", request, h.WorkflowServiceServer.RespondActivityTaskCompletedById)
}
func (h *validatedWorkflowService) RespondActivityTaskFailed(ctx context.Context, request *pb1.RespondActivityTaskFailedRequest) (*pb1.RespondActivityTaskFailedResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/RespondActivityTaskFailed", request, h.WorkflowServiceServer.RespondActivityTaskFailed)
}
func (h *validatedWorkflowService) RespondActivityTaskFailedById(ctx context.Context, request *pb1.RespondActivityTaskFailedByIdRequest) (*pb1.RespondActivityTaskFailedByIdResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/RespondActivityTaskFailedById", request, h.WorkflowServiceServer.RespondActivityTaskFailedById)
}
func (h *validatedWorkflowService) RespondActivityTaskCanceled(ctx context.Context, request *pb1.RespondActivityTaskCanceledRequest) (*pb1.RespondActivityTaskCanceledResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/RespondActivityTaskCanceled", request, h.WorkflowServiceServer.RespondActivityTaskCanceled)
}
func (h *validatedWorkflowService) RespondActivityTaskCanceledById(ctx context.Context, request *pb1.RespondActivityTaskCanceledByIdRequest) (*pb1.RespondActivityTaskCanceledByIdResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/RespondActivityTaskCanceledById", request, h.WorkflowServiceServer.RespondActivityTaskCanceledById)
}
func (h *validatedWorkflowService) RequestCancelWorkflowExecution(ctx context.Context, request *pb1.RequestCancelWorkflowExecutionRequest) (*pb1.RequestCancelWorkflowExecutionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/RequestCancelWorkflowExecution", request, h.WorkflowServiceServer.RequestCancelWorkflowExecution)
}
func (h *validatedWorkflowService) SignalWorkflowExecution(ctx context.Context, request *pb1.SignalWorkflowExecutionRequest) (*pb1.SignalWorkflowExecutionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/SignalWorkflowExecution", request, h.WorkflowServiceServer.SignalWorkflowExecution)
}
func (h *validatedWorkflowService) SignalWithStartWorkflowExecution(ctx context.Context, request *pb1.SignalWithStartWorkflowExecutionRequest) (*pb1.SignalWithStartWorkflowExecutionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/SignalWithStartWorkflowExecution", request, h.WorkflowServiceServer.SignalWithStartWorkflowExecution)
}
func (h *validatedWorkflowService) ResetWorkflowExecution(ctx context.Context, request *pb1.ResetWorkflowExecutionRequest) (*pb1.ResetWorkflowExecutionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/ResetWorkflowExecution", request, h.WorkflowServiceServer.ResetWorkflowExecution)
}
func (h *validatedWorkflowService) TerminateWorkflowExecution(ctx context.Context, request *pb1.TerminateWorkflowExecutionRequest) (*pb1.TerminateWorkflowExecutionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/TerminateWorkflowExecution", request, h.WorkflowServiceServer.TerminateWorkflowExecution)
}
func (h *validatedWorkflowService) DeleteWorkflowExecution(ctx context.Context, request *pb1.DeleteWorkflowExecutionRequest) (*pb1.DeleteWorkflowExecutionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/DeleteWorkflowExecution", request, h.WorkflowServiceServer.DeleteWorkflowExecution)
}
func (h *validatedWorkflowService) ListOpenWorkflowExecutions(ctx context.Context, request *pb1.ListOpenWorkflowExecutionsRequest) (*pb1.ListOpenWorkflowExecutionsResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/ListOpenWorkflowExecutions", request, h.WorkflowServiceServer.ListOpenWorkflowExecutions)
}
func (h *validatedWorkflowService) ListClosedWorkflowExecutions(ctx context.Context, request *pb1.ListClosedWorkflowExecutionsRequest) (*pb1.ListClosedWorkflowExecutionsResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/ListClosedWorkflowExecutions", request, h.WorkflowServiceServer.ListClosedWorkflowExecutions)
}
func (h *validatedWorkflowService) ListWorkflowExecutions(ctx context.Context, request *pb1.ListWorkflowExecutionsRequest) (*pb1.ListWorkflowExecutionsResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/ListWorkflowExecutions", request, h.WorkflowServiceServer.ListWorkflowExecutions)
}
func (h *validatedWorkflowService) ListArchivedWorkflowExecutions(ctx context.Context, request *pb1.ListArchivedWorkflowExecutionsRequest) (*pb1.ListArchivedWorkflowExecutionsResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/ListArchivedWorkflowExecutions", request, h.WorkflowServiceServer.ListArchivedWorkflowExecutions)
}
func (h *validatedWorkflowService) ScanWorkflowExecutions(ctx context.Context, request *pb1.ScanWorkflowExecutionsRequest) (*pb1.ScanWorkflowExecutionsResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/ScanWorkflowExecutions", request, h.WorkflowServiceServer.ScanWorkflowExecutions)
}
func (h *validatedWorkflowService) CountWorkflowExecutions(ctx context.Context, request *pb1.CountWorkflowExecutionsRequest) (*pb1.CountWorkflowExecutionsResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/CountWorkflowExecutions", request, h.WorkflowServiceServer.CountWorkflowExecutions)
}
func (h *validatedWorkflowService) GetSearchAttributes(ctx context.Context, request *pb1.GetSearchAttributesRequest) (*pb1.GetSearchAttributesResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/GetSearchAttributes", request, h.WorkflowServiceServer.GetSearchAttributes)
}
func (h *validatedWorkflowService) RespondQueryTaskCompleted(ctx context.Context, request *pb1.RespondQueryTaskCompletedRequest) (*pb1.RespondQueryTaskCompletedResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/RespondQueryTaskCompleted", request, h.WorkflowServiceServer.RespondQueryTaskCompleted)
}
func (h *validatedWorkflowService) ResetStickyTaskQueue(ctx context.Context, request *pb1.ResetStickyTaskQueueRequest) (*pb1.ResetStickyTaskQueueResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/ResetStickyTaskQueue", request, h.WorkflowServiceServer.ResetStickyTaskQueue)
}
func (h *validatedWorkflowService) ShutdownWorker(ctx context.Context, request *pb1.ShutdownWorkerRequest) (*pb1.ShutdownWorkerResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/ShutdownWorker", request, h.WorkflowServiceServer.ShutdownWorker)
}
func (h *validatedWorkflowService) QueryWorkflow(ctx context.Context, request *pb1.QueryWorkflowRequest) (*pb1.QueryWorkflowResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/QueryWorkflow", request, h.WorkflowServiceServer.QueryWorkflow)
}
func (h *validatedWorkflowService) DescribeWorkflowExecution(ctx context.Context, request *pb1.DescribeWorkflowExecutionRequest) (*pb1.DescribeWorkflowExecutionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/DescribeWorkflowExecution", request, h.WorkflowServiceServer.DescribeWorkflowExecution)
}
func (h *validatedWorkflowService) DescribeTaskQueue(ctx context.Context, request *pb1.DescribeTaskQueueRequest) (*pb1.DescribeTaskQueueResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/DescribeTaskQueue", request, h.WorkflowServiceServer.DescribeTaskQueue)
}
func (h *validatedWorkflowService) GetClusterInfo(ctx context.Context, request *pb1.GetClusterInfoRequest) (*pb1.GetClusterInfoResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/GetClusterInfo", request, h.WorkflowServiceServer.GetClusterInfo)
}
func (h *validatedWorkflowService) GetSystemInfo(ctx context.Context, request *pb1.GetSystemInfoRequest) (*pb1.GetSystemInfoResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/GetSystemInfo", request, h.WorkflowServiceServer.GetSystemInfo)
}
func (h *validatedWorkflowService) ListTaskQueuePartitions(ctx context.Context, request *pb1.ListTaskQueuePartitionsRequest) (*pb1.ListTaskQueuePartitionsResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/ListTaskQueuePartitions", request, h.WorkflowServiceServer.ListTaskQueuePartitions)
}
func (h *validatedWorkflowService) CreateSchedule(ctx context.Context, request *pb1.CreateScheduleRequest) (*pb1.CreateScheduleResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/CreateSchedule", request, h.WorkflowServiceServer.CreateSchedule)
}
func (h *validatedWorkflowService) DescribeSchedule(ctx context.Context, request *pb1.DescribeScheduleRequest) (*pb1.DescribeScheduleResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/DescribeSchedule", request, h.WorkflowServiceServer.DescribeSchedule)
}
func (h *validatedWorkflowService) UpdateSchedule(ctx context.Context, request *pb1.UpdateScheduleRequest) (*pb1.UpdateScheduleResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/UpdateSchedule", request, h.WorkflowServiceServer.UpdateSchedule)
}
func (h *validatedWorkflowService) PatchSchedule(ctx context.Context, request *pb1.PatchScheduleRequest) (*pb1.PatchScheduleResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/PatchSchedule", request, h.WorkflowServiceServer.PatchSchedule)
}
func (h *validatedWorkflowService) ListScheduleMatchingTimes(ctx context.Context, request *pb1.ListScheduleMatchingTimesRequest) (*pb1.ListScheduleMatchingTimesResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/ListScheduleMatchingTimes", request, h.WorkflowServiceServer.ListScheduleMatchingTimes)
}
func (h *validatedWorkflowService) DeleteSchedule(ctx context.Context, request *pb1.DeleteScheduleRequest) (*pb1.DeleteScheduleResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/DeleteSchedule", request, h.WorkflowServiceServer.DeleteSchedule)
}
func (h *validatedWorkflowService) ListSchedules(ctx context.Context, request *pb1.ListSchedulesRequest) (*pb1.ListSchedulesResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/ListSchedules", request, h.WorkflowServiceServer.ListSchedules)
}
func (h *validatedWorkflowService) CountSchedules(ctx context.Context, request *pb1.CountSchedulesRequest) (*pb1.CountSchedulesResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/CountSchedules", request, h.WorkflowServiceServer.CountSchedules)
}
func (h *validatedWorkflowService) UpdateWorkerBuildIdCompatibility(ctx context.Context, request *pb1.UpdateWorkerBuildIdCompatibilityRequest) (*pb1.UpdateWorkerBuildIdCompatibilityResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/UpdateWorkerBuildIdCompatibility", request, h.WorkflowServiceServer.UpdateWorkerBuildIdCompatibility)
}
func (h *validatedWorkflowService) GetWorkerBuildIdCompatibility(ctx context.Context, request *pb1.GetWorkerBuildIdCompatibilityRequest) (*pb1.GetWorkerBuildIdCompatibilityResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/GetWorkerBuildIdCompatibility", request, h.WorkflowServiceServer.GetWorkerBuildIdCompatibility)
}
func (h *validatedWorkflowService) UpdateWorkerVersioningRules(ctx context.Context, request *pb1.UpdateWorkerVersioningRulesRequest) (*pb1.UpdateWorkerVersioningRulesResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/UpdateWorkerVersioningRules", request, h.WorkflowServiceServer.UpdateWorkerVersioningRules)
}
func (h *validatedWorkflowService) GetWorkerVersioningRules(ctx context.Context, request *pb1.GetWorkerVersioningRulesRequest) (*pb1.GetWorkerVersioningRulesResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/GetWorkerVersioningRules", request, h.WorkflowServiceServer.GetWorkerVersioningRules)
}
func (h *validatedWorkflowService) GetWorkerTaskReachability(ctx context.Context, request *pb1.GetWorkerTaskReachabilityRequest) (*pb1.GetWorkerTaskReachabilityResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/GetWorkerTaskReachability", request, h.WorkflowServiceServer.GetWorkerTaskReachability)
}
func (h *validatedWorkflowService) DescribeDeployment(ctx context.Context, request *pb1.DescribeDeploymentRequest) (*pb1.DescribeDeploymentResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/DescribeDeployment", request, h.WorkflowServiceServer.DescribeDeployment)
}
func (h *validatedWorkflowService) DescribeWorkerDeploymentVersion(ctx context.Context, request *pb1.DescribeWorkerDeploymentVersionRequest) (*pb1.DescribeWorkerDeploymentVersionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/DescribeWorkerDeploymentVersion", request, h.WorkflowServiceServer.DescribeWorkerDeploymentVersion)
}
func (h *validatedWorkflowService) ListDeployments(ctx context.Context, request *pb1.ListDeploymentsRequest) (*pb1.ListDeploymentsResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/ListDeployments", request, h.WorkflowServiceServer.ListDeployments)
}
func (h *validatedWorkflowService) GetDeploymentReachability(ctx context.Context, request *pb1.GetDeploymentReachabilityRequest) (*pb1.GetDeploymentReachabilityResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/GetDeploymentReachability", request, h.WorkflowServiceServer.GetDeploymentReachability)
}
func (h *validatedWorkflowService) GetCurrentDeployment(ctx context.Context, request *pb1.GetCurrentDeploymentRequest) (*pb1.GetCurrentDeploymentResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/GetCurrentDeployment", request, h.WorkflowServiceServer.GetCurrentDeployment)
}
func (h *validatedWorkflowService) SetCurrentDeployment(ctx context.Context, request *pb1.SetCurrentDeploymentRequest) (*pb1.SetCurrentDeploymentResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/SetCurrentDeployment", request, h.WorkflowServiceServer.SetCurrentDeployment)
}
func (h *validatedWorkflowService) SetWorkerDeploymentCurrentVersion(ctx context.Context, request *pb1.SetWorkerDeploymentCurrentVersionRequest) (*pb1.SetWorkerDeploymentCurrentVersionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/SetWorkerDeploymentCurrentVersion", request, h.WorkflowServiceServer.SetWorkerDeploymentCurrentVersion)
}
func (h *validatedWorkflowService) DescribeWorkerDeployment(ctx context.Context, request *pb1.DescribeWorkerDeploymentRequest) (*pb1.DescribeWorkerDeploymentResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/DescribeWorkerDeployment", request, h.WorkflowServiceServer.DescribeWorkerDeployment)
}
func (h *validatedWorkflowService) DeleteWorkerDeployment(ctx context.Context, request *pb1.DeleteWorkerDeploymentRequest) (*pb1.DeleteWorkerDeploymentResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/DeleteWorkerDeployment", request, h.WorkflowServiceServer.DeleteWorkerDeployment)
}
func (h *validatedWorkflowService) DeleteWorkerDeploymentVersion(ctx context.Context, request *pb1.DeleteWorkerDeploymentVersionRequest) (*pb1.DeleteWorkerDeploymentVersionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/DeleteWorkerDeploymentVersion", request, h.WorkflowServiceServer.DeleteWorkerDeploymentVersion)
}
func (h *validatedWorkflowService) SetWorkerDeploymentRampingVersion(ctx context.Context, request *pb1.SetWorkerDeploymentRampingVersionRequest) (*pb1.SetWorkerDeploymentRampingVersionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/SetWorkerDeploymentRampingVersion", request, h.WorkflowServiceServer.SetWorkerDeploymentRampingVersion)
}
func (h *validatedWorkflowService) ListWorkerDeployments(ctx context.Context, request *pb1.ListWorkerDeploymentsRequest) (*pb1.ListWorkerDeploymentsResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/ListWorkerDeployments", request, h.WorkflowServiceServer.ListWorkerDeployments)
}
func (h *validatedWorkflowService) CreateWorkerDeployment(ctx context.Context, request *pb1.CreateWorkerDeploymentRequest) (*pb1.CreateWorkerDeploymentResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/CreateWorkerDeployment", request, h.WorkflowServiceServer.CreateWorkerDeployment)
}
func (h *validatedWorkflowService) CreateWorkerDeploymentVersion(ctx context.Context, request *pb1.CreateWorkerDeploymentVersionRequest) (*pb1.CreateWorkerDeploymentVersionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/CreateWorkerDeploymentVersion", request, h.WorkflowServiceServer.CreateWorkerDeploymentVersion)
}
func (h *validatedWorkflowService) UpdateWorkerDeploymentVersionComputeConfig(ctx context.Context, request *pb1.UpdateWorkerDeploymentVersionComputeConfigRequest) (*pb1.UpdateWorkerDeploymentVersionComputeConfigResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/UpdateWorkerDeploymentVersionComputeConfig", request, h.WorkflowServiceServer.UpdateWorkerDeploymentVersionComputeConfig)
}
func (h *validatedWorkflowService) ValidateWorkerDeploymentVersionComputeConfig(ctx context.Context, request *pb1.ValidateWorkerDeploymentVersionComputeConfigRequest) (*pb1.ValidateWorkerDeploymentVersionComputeConfigResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/ValidateWorkerDeploymentVersionComputeConfig", request, h.WorkflowServiceServer.ValidateWorkerDeploymentVersionComputeConfig)
}
func (h *validatedWorkflowService) UpdateWorkerDeploymentVersionMetadata(ctx context.Context, request *pb1.UpdateWorkerDeploymentVersionMetadataRequest) (*pb1.UpdateWorkerDeploymentVersionMetadataResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/UpdateWorkerDeploymentVersionMetadata", request, h.WorkflowServiceServer.UpdateWorkerDeploymentVersionMetadata)
}
func (h *validatedWorkflowService) SetWorkerDeploymentManager(ctx context.Context, request *pb1.SetWorkerDeploymentManagerRequest) (*pb1.SetWorkerDeploymentManagerResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/SetWorkerDeploymentManager", request, h.WorkflowServiceServer.SetWorkerDeploymentManager)
}
func (h *validatedWorkflowService) UpdateWorkflowExecution(ctx context.Context, request *pb1.UpdateWorkflowExecutionRequest) (*pb1.UpdateWorkflowExecutionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/UpdateWorkflowExecution", request, h.WorkflowServiceServer.UpdateWorkflowExecution)
}
func (h *validatedWorkflowService) PollWorkflowExecutionUpdate(ctx context.Context, request *pb1.PollWorkflowExecutionUpdateRequest) (*pb1.PollWorkflowExecutionUpdateResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/PollWorkflowExecutionUpdate", request, h.WorkflowServiceServer.PollWorkflowExecutionUpdate)
}
func (h *validatedWorkflowService) StartBatchOperation(ctx context.Context, request *pb1.StartBatchOperationRequest) (*pb1.StartBatchOperationResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/StartBatchOperation", request, h.WorkflowServiceServer.StartBatchOperation)
}
func (h *validatedWorkflowService) StopBatchOperation(ctx context.Context, request *pb1.StopBatchOperationRequest) (*pb1.StopBatchOperationResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/StopBatchOperation", request, h.WorkflowServiceServer.StopBatchOperation)
}
func (h *validatedWorkflowService) DescribeBatchOperation(ctx context.Context, request *pb1.DescribeBatchOperationRequest) (*pb1.DescribeBatchOperationResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/DescribeBatchOperation", request, h.WorkflowServiceServer.DescribeBatchOperation)
}
func (h *validatedWorkflowService) ListBatchOperations(ctx context.Context, request *pb1.ListBatchOperationsRequest) (*pb1.ListBatchOperationsResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/ListBatchOperations", request, h.WorkflowServiceServer.ListBatchOperations)
}
func (h *validatedWorkflowService) PollNexusTaskQueue(ctx context.Context, request *pb1.PollNexusTaskQueueRequest) (*pb1.PollNexusTaskQueueResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/PollNexusTaskQueue", request, h.WorkflowServiceServer.PollNexusTaskQueue)
}
func (h *validatedWorkflowService) RespondNexusTaskCompleted(ctx context.Context, request *pb1.RespondNexusTaskCompletedRequest) (*pb1.RespondNexusTaskCompletedResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/RespondNexusTaskCompleted", request, h.WorkflowServiceServer.RespondNexusTaskCompleted)
}
func (h *validatedWorkflowService) RespondNexusTaskFailed(ctx context.Context, request *pb1.RespondNexusTaskFailedRequest) (*pb1.RespondNexusTaskFailedResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/RespondNexusTaskFailed", request, h.WorkflowServiceServer.RespondNexusTaskFailed)
}
func (h *validatedWorkflowService) UpdateActivityOptions(ctx context.Context, request *pb1.UpdateActivityOptionsRequest) (*pb1.UpdateActivityOptionsResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/UpdateActivityOptions", request, h.WorkflowServiceServer.UpdateActivityOptions)
}
func (h *validatedWorkflowService) UpdateWorkflowExecutionOptions(ctx context.Context, request *pb1.UpdateWorkflowExecutionOptionsRequest) (*pb1.UpdateWorkflowExecutionOptionsResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/UpdateWorkflowExecutionOptions", request, h.WorkflowServiceServer.UpdateWorkflowExecutionOptions)
}
func (h *validatedWorkflowService) PauseActivity(ctx context.Context, request *pb1.PauseActivityRequest) (*pb1.PauseActivityResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/PauseActivity", request, h.WorkflowServiceServer.PauseActivity)
}
func (h *validatedWorkflowService) UnpauseActivity(ctx context.Context, request *pb1.UnpauseActivityRequest) (*pb1.UnpauseActivityResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/UnpauseActivity", request, h.WorkflowServiceServer.UnpauseActivity)
}
func (h *validatedWorkflowService) ResetActivity(ctx context.Context, request *pb1.ResetActivityRequest) (*pb1.ResetActivityResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/ResetActivity", request, h.WorkflowServiceServer.ResetActivity)
}
func (h *validatedWorkflowService) CreateWorkflowRule(ctx context.Context, request *pb1.CreateWorkflowRuleRequest) (*pb1.CreateWorkflowRuleResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/CreateWorkflowRule", request, h.WorkflowServiceServer.CreateWorkflowRule)
}
func (h *validatedWorkflowService) DescribeWorkflowRule(ctx context.Context, request *pb1.DescribeWorkflowRuleRequest) (*pb1.DescribeWorkflowRuleResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/DescribeWorkflowRule", request, h.WorkflowServiceServer.DescribeWorkflowRule)
}
func (h *validatedWorkflowService) DeleteWorkflowRule(ctx context.Context, request *pb1.DeleteWorkflowRuleRequest) (*pb1.DeleteWorkflowRuleResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/DeleteWorkflowRule", request, h.WorkflowServiceServer.DeleteWorkflowRule)
}
func (h *validatedWorkflowService) ListWorkflowRules(ctx context.Context, request *pb1.ListWorkflowRulesRequest) (*pb1.ListWorkflowRulesResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/ListWorkflowRules", request, h.WorkflowServiceServer.ListWorkflowRules)
}
func (h *validatedWorkflowService) TriggerWorkflowRule(ctx context.Context, request *pb1.TriggerWorkflowRuleRequest) (*pb1.TriggerWorkflowRuleResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/TriggerWorkflowRule", request, h.WorkflowServiceServer.TriggerWorkflowRule)
}
func (h *validatedWorkflowService) RecordWorkerHeartbeat(ctx context.Context, request *pb1.RecordWorkerHeartbeatRequest) (*pb1.RecordWorkerHeartbeatResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/RecordWorkerHeartbeat", request, h.WorkflowServiceServer.RecordWorkerHeartbeat)
}
func (h *validatedWorkflowService) ListWorkers(ctx context.Context, request *pb1.ListWorkersRequest) (*pb1.ListWorkersResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/ListWorkers", request, h.WorkflowServiceServer.ListWorkers)
}
func (h *validatedWorkflowService) CountWorkers(ctx context.Context, request *pb1.CountWorkersRequest) (*pb1.CountWorkersResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/CountWorkers", request, h.WorkflowServiceServer.CountWorkers)
}
func (h *validatedWorkflowService) UpdateTaskQueueConfig(ctx context.Context, request *pb1.UpdateTaskQueueConfigRequest) (*pb1.UpdateTaskQueueConfigResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/UpdateTaskQueueConfig", request, h.WorkflowServiceServer.UpdateTaskQueueConfig)
}
func (h *validatedWorkflowService) FetchWorkerConfig(ctx context.Context, request *pb1.FetchWorkerConfigRequest) (*pb1.FetchWorkerConfigResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/FetchWorkerConfig", request, h.WorkflowServiceServer.FetchWorkerConfig)
}
func (h *validatedWorkflowService) UpdateWorkerConfig(ctx context.Context, request *pb1.UpdateWorkerConfigRequest) (*pb1.UpdateWorkerConfigResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/UpdateWorkerConfig", request, h.WorkflowServiceServer.UpdateWorkerConfig)
}
func (h *validatedWorkflowService) DescribeWorker(ctx context.Context, request *pb1.DescribeWorkerRequest) (*pb1.DescribeWorkerResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/DescribeWorker", request, h.WorkflowServiceServer.DescribeWorker)
}
func (h *validatedWorkflowService) PauseWorkflowExecution(ctx context.Context, request *pb1.PauseWorkflowExecutionRequest) (*pb1.PauseWorkflowExecutionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/PauseWorkflowExecution", request, h.WorkflowServiceServer.PauseWorkflowExecution)
}
func (h *validatedWorkflowService) UnpauseWorkflowExecution(ctx context.Context, request *pb1.UnpauseWorkflowExecutionRequest) (*pb1.UnpauseWorkflowExecutionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/UnpauseWorkflowExecution", request, h.WorkflowServiceServer.UnpauseWorkflowExecution)
}
func (h *validatedWorkflowService) StartActivityExecution(ctx context.Context, request *pb1.StartActivityExecutionRequest) (*pb1.StartActivityExecutionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/StartActivityExecution", request, h.WorkflowServiceServer.StartActivityExecution)
}
func (h *validatedWorkflowService) StartNexusOperationExecution(ctx context.Context, request *pb1.StartNexusOperationExecutionRequest) (*pb1.StartNexusOperationExecutionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/StartNexusOperationExecution", request, h.WorkflowServiceServer.StartNexusOperationExecution)
}
func (h *validatedWorkflowService) DescribeActivityExecution(ctx context.Context, request *pb1.DescribeActivityExecutionRequest) (*pb1.DescribeActivityExecutionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/DescribeActivityExecution", request, h.WorkflowServiceServer.DescribeActivityExecution)
}
func (h *validatedWorkflowService) DescribeNexusOperationExecution(ctx context.Context, request *pb1.DescribeNexusOperationExecutionRequest) (*pb1.DescribeNexusOperationExecutionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/DescribeNexusOperationExecution", request, h.WorkflowServiceServer.DescribeNexusOperationExecution)
}
func (h *validatedWorkflowService) PollActivityExecution(ctx context.Context, request *pb1.PollActivityExecutionRequest) (*pb1.PollActivityExecutionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/PollActivityExecution", request, h.WorkflowServiceServer.PollActivityExecution)
}
func (h *validatedWorkflowService) PollNexusOperationExecution(ctx context.Context, request *pb1.PollNexusOperationExecutionRequest) (*pb1.PollNexusOperationExecutionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/PollNexusOperationExecution", request, h.WorkflowServiceServer.PollNexusOperationExecution)
}
func (h *validatedWorkflowService) ListActivityExecutions(ctx context.Context, request *pb1.ListActivityExecutionsRequest) (*pb1.ListActivityExecutionsResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/ListActivityExecutions", request, h.WorkflowServiceServer.ListActivityExecutions)
}
func (h *validatedWorkflowService) ListNexusOperationExecutions(ctx context.Context, request *pb1.ListNexusOperationExecutionsRequest) (*pb1.ListNexusOperationExecutionsResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/ListNexusOperationExecutions", request, h.WorkflowServiceServer.ListNexusOperationExecutions)
}
func (h *validatedWorkflowService) CountActivityExecutions(ctx context.Context, request *pb1.CountActivityExecutionsRequest) (*pb1.CountActivityExecutionsResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/CountActivityExecutions", request, h.WorkflowServiceServer.CountActivityExecutions)
}
func (h *validatedWorkflowService) CountNexusOperationExecutions(ctx context.Context, request *pb1.CountNexusOperationExecutionsRequest) (*pb1.CountNexusOperationExecutionsResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/CountNexusOperationExecutions", request, h.WorkflowServiceServer.CountNexusOperationExecutions)
}
func (h *validatedWorkflowService) RequestCancelActivityExecution(ctx context.Context, request *pb1.RequestCancelActivityExecutionRequest) (*pb1.RequestCancelActivityExecutionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/RequestCancelActivityExecution", request, h.WorkflowServiceServer.RequestCancelActivityExecution)
}
func (h *validatedWorkflowService) RequestCancelNexusOperationExecution(ctx context.Context, request *pb1.RequestCancelNexusOperationExecutionRequest) (*pb1.RequestCancelNexusOperationExecutionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/RequestCancelNexusOperationExecution", request, h.WorkflowServiceServer.RequestCancelNexusOperationExecution)
}
func (h *validatedWorkflowService) TerminateActivityExecution(ctx context.Context, request *pb1.TerminateActivityExecutionRequest) (*pb1.TerminateActivityExecutionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/TerminateActivityExecution", request, h.WorkflowServiceServer.TerminateActivityExecution)
}
func (h *validatedWorkflowService) DeleteActivityExecution(ctx context.Context, request *pb1.DeleteActivityExecutionRequest) (*pb1.DeleteActivityExecutionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/DeleteActivityExecution", request, h.WorkflowServiceServer.DeleteActivityExecution)
}
func (h *validatedWorkflowService) PauseActivityExecution(ctx context.Context, request *pb1.PauseActivityExecutionRequest) (*pb1.PauseActivityExecutionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/PauseActivityExecution", request, h.WorkflowServiceServer.PauseActivityExecution)
}
func (h *validatedWorkflowService) ResetActivityExecution(ctx context.Context, request *pb1.ResetActivityExecutionRequest) (*pb1.ResetActivityExecutionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/ResetActivityExecution", request, h.WorkflowServiceServer.ResetActivityExecution)
}
func (h *validatedWorkflowService) UnpauseActivityExecution(ctx context.Context, request *pb1.UnpauseActivityExecutionRequest) (*pb1.UnpauseActivityExecutionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/UnpauseActivityExecution", request, h.WorkflowServiceServer.UnpauseActivityExecution)
}
func (h *validatedWorkflowService) UpdateActivityExecutionOptions(ctx context.Context, request *pb1.UpdateActivityExecutionOptionsRequest) (*pb1.UpdateActivityExecutionOptionsResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/UpdateActivityExecutionOptions", request, h.WorkflowServiceServer.UpdateActivityExecutionOptions)
}
func (h *validatedWorkflowService) TerminateNexusOperationExecution(ctx context.Context, request *pb1.TerminateNexusOperationExecutionRequest) (*pb1.TerminateNexusOperationExecutionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/TerminateNexusOperationExecution", request, h.WorkflowServiceServer.TerminateNexusOperationExecution)
}
func (h *validatedWorkflowService) DeleteNexusOperationExecution(ctx context.Context, request *pb1.DeleteNexusOperationExecutionRequest) (*pb1.DeleteNexusOperationExecutionResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/DeleteNexusOperationExecution", request, h.WorkflowServiceServer.DeleteNexusOperationExecution)
}
func (h *validatedWorkflowService) PollWorkflowExecutionTimeSkipping(ctx context.Context, request *pb1.PollWorkflowExecutionTimeSkippingRequest) (*pb1.PollWorkflowExecutionTimeSkippingResponse, error) {
	return ValidateCall(ctx, h.registry, "/temporal.api.workflowservice.v1.WorkflowService/PollWorkflowExecutionTimeSkipping", request, h.WorkflowServiceServer.PollWorkflowExecutionTimeSkipping)
}
