// genrequestvalidation generates shared boundaries for every public API service.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"reflect"
	"slices"
	"strings"

	apiregistry "go.temporal.io/api/temporalproto/registry"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/reflect/protoregistry"
	"google.golang.org/protobuf/types/descriptorpb"
)

func main() {
	out := flag.String("out", "services_gen.go", "generated service boundaries")
	check := flag.Bool("check", false, "fail if generated code is stale")
	flag.Parse()
	if err := run(*out, *check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(out string, check bool) error {
	generated, err := generate(apiregistry.Services())
	if err != nil {
		return err
	}
	if !check {
		return os.WriteFile(out, generated, 0o644)
	}
	current, err := os.ReadFile(out)
	if err != nil {
		return err
	}
	if !bytes.Equal(current, generated) {
		return fmt.Errorf("%s is stale; run go generate ./common/validation", out)
	}
	return nil
}

func generate(services []protoreflect.ServiceDescriptor) ([]byte, error) {
	imports := map[string]string{}
	var body bytes.Buffer
	var methodNames []string
	for _, service := range services {
		options, ok := service.ParentFile().Options().(*descriptorpb.FileOptions)
		if !ok {
			return nil, fmt.Errorf("%s has invalid file options", service.FullName())
		}
		pkg, _, _ := strings.Cut(options.GetGoPackage(), ";")
		if pkg == "" {
			return nil, fmt.Errorf("%s has no Go package", service.FullName())
		}
		alias, ok := imports[pkg]
		if !ok {
			alias = fmt.Sprintf("pb%d", len(imports))
			imports[pkg] = alias
		}
		name := string(service.Name())
		fmt.Fprintf(&body, "type validated%s struct { %s.%sServer; registry *Registry }\n", name, alias, name)
		fmt.Fprintf(&body, "func Wrap%s(handler %s.%sServer, registry *Registry) %s.%sServer { return &validated%s{%sServer: handler, registry: registry} }\n", name, alias, name, alias, name, name, name)
		for i := range service.Methods().Len() {
			method := service.Methods().Get(i)
			if method.IsStreamingClient() || method.IsStreamingServer() {
				continue
			}
			methodNames = append(methodNames, "/"+string(service.FullName())+"/"+string(method.Name()))
			input, err := goMessageType(method.Input(), imports)
			if err != nil {
				return nil, err
			}
			output, err := goMessageType(method.Output(), imports)
			if err != nil {
				return nil, err
			}
			fmt.Fprintf(&body, "func (h *validated%s) %s(ctx context.Context, request *%s) (*%s, error) { return ValidateCall(ctx, h.registry, %q, request, h.%sServer.%s) }\n", name, method.Name(), input, output, "/"+string(service.FullName())+"/"+string(method.Name()), name, method.Name())
		}
	}
	var out bytes.Buffer
	out.WriteString("// Code generated by genrequestvalidation. DO NOT EDIT.\npackage validation\nimport (\n\"context\"\n\n")
	paths := make([]string, 0, len(imports))
	for path := range imports {
		paths = append(paths, path)
	}
	slices.Sort(paths)
	for _, path := range paths {
		fmt.Fprintf(&out, "%s %q\n", imports[path], path)
	}
	out.WriteString(")\n")
	out.WriteString("var generatedUnaryMethods = map[string]struct{}{\n")
	for _, name := range methodNames {
		fmt.Fprintf(&out, "%q: {},\n", name)
	}
	out.WriteString("}\n")
	out.Write(body.Bytes())
	return format.Source(out.Bytes())
}

func goMessageType(message protoreflect.MessageDescriptor, imports map[string]string) (string, error) {
	typ, err := protoregistry.GlobalTypes.FindMessageByName(message.FullName())
	if err != nil {
		return "", err
	}
	goType := reflect.TypeOf(typ.New().Interface()).Elem()
	alias, ok := imports[goType.PkgPath()]
	if !ok {
		alias = fmt.Sprintf("pb%d", len(imports))
		imports[goType.PkgPath()] = alias
	}
	return alias + "." + goType.Name(), nil
}
